import type {
  MojoSourceProfileCallRow,
  MojoSourceProfileParameterContract,
} from "./source-profile-selection.js";
import {
  jsCallbackRow,
  jsConstructorRows,
  jsInstanceParameterRow,
  jsInstanceRows,
  jsReceiverArrayRow,
  jsReceiverFunctionRow,
  jsStaticRows,
  receiverArgument,
  receiverType,
  snakeCase,
  sourceErrorRows,
} from "./source-profile-row-builders.js";

export const mojoSourceProfileCallRows: readonly MojoSourceProfileCallRow[] = Object.freeze([
  ...sourceErrorRows,
  ...jsConstructorRows,
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "ArrayConstructor",
    member: "from",
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["selected-argument"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "array_from",
    }),
    resultContract: Object.freeze({
      kind: "constructed-explicit-arguments",
      indexes: Object.freeze([0]),
    }),
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "ArrayConstructor",
    member: "from",
    argumentCount: 2,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(([
      "selected-argument",
      "selected-argument",
    ])),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "array_from_map_value",
    }),
    resultContract: Object.freeze({
      kind: "constructed-explicit-arguments",
      indexes: Object.freeze([1]),
    }),
    callback: Object.freeze({
      parameterIndex: 1,
      result: "preserve",
      errorMode: "propagate",
      variants: Object.freeze([
        Object.freeze({ arity: 1, targetName: "array_from_map_value" }),
        Object.freeze({ arity: 2, targetName: "array_from_map_with_index" }),
      ]),
    }),
  }),
  ...jsInstanceRows("String", "imm", [
    "at", "charAt", "charCodeAt", "codePointAt", "concat", "endsWith", "includes",
    "indexOf", "lastIndexOf", "padEnd", "padStart",
    ["repeat", "repeat", true], "slice", "startsWith",
    "substr", "substring", ["toLowerCase", "to_lower_case", true], "toString",
    ["toUpperCase", "to_upper_case", true], "toWellFormed",
    "trim", "trimEnd", "trimLeft", "trimRight", "trimStart", "valueOf", "isWellFormed",
  ]),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "String",
    member: "replace",
    target: Object.freeze({ kind: "instance", name: "replace", receiver: "imm" }),
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string", "js-string"]),
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "String",
    member: "replaceAll",
    target: Object.freeze({ kind: "instance", name: "replace_all", receiver: "imm" }),
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string", "js-string"]),
    raises: true,
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "String",
    member: "split",
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "string_split",
      receiver: "imm",
    }),
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string", "float64"]),
  }),
  ...jsInstanceRows("Array", "mut", ["copyWithin", "pop", "reverse", "shift"]),
  jsInstanceParameterRow("Array", "fill", "mut", [receiverArgument(0), "float64", "float64"]),
  jsInstanceParameterRow("Array", "push", "mut", [receiverArgument(0)]),
  jsInstanceParameterRow("Array", "splice", "mut", ["float64", "float64", receiverArgument(0)]),
  jsInstanceParameterRow("Array", "unshift", "mut", [receiverArgument(0)]),
  ...["Array", "ReadonlyArray"].flatMap((owner) => [
    jsInstanceParameterRow(owner, "at", "imm", ["float64"]),
    jsInstanceParameterRow(owner, "includes", "imm", [receiverArgument(0), "float64"]),
    jsInstanceParameterRow(owner, "indexOf", "imm", [receiverArgument(0), "float64"]),
    jsInstanceParameterRow(owner, "join", "imm", ["js-string"]),
    jsInstanceParameterRow(owner, "lastIndexOf", "imm", [receiverArgument(0), "float64"]),
    jsInstanceParameterRow(owner, "slice", "imm", ["float64", "float64"]),
  ]),
  ...["Array", "ReadonlyArray"].flatMap((owner) => [
    jsCallbackRow(owner, "map", "imm", "preserve", [
      "array_map_zero", "array_map_value", "array_map_with_index", "array_map_with_array",
    ]),
    jsCallbackRow(owner, "forEach", "imm", "preserve", [
      "array_for_each_zero", "array_for_each_value", "array_for_each_value_index", "array_for_each_with_array",
    ]),
    ...["filter", "some", "every", "find", "findIndex", "findLast", "findLastIndex"].map((member) =>
      jsCallbackRow(owner, member, "imm", "bool", [
        `array_${snakeCase(member)}_zero`,
        `array_${snakeCase(member)}_value`,
        `array_${snakeCase(member)}_with_index`,
        `array_${snakeCase(member)}_with_array`,
      ])),
    jsCallbackRow(owner, "reduce", "imm", "preserve", [
      "array_reduce_from_first_zero",
      "array_reduce_from_first_accumulator",
      "array_reduce_from_first_value",
      "array_reduce_from_first_with_index",
      "array_reduce_from_first_with_array",
    ], 1, "native"),
    jsCallbackRow(owner, "reduce", "imm", "preserve", [
      "array_reduce_initial_zero",
      "array_reduce_initial_accumulator",
      "array_reduce_initial_value",
      "array_reduce_initial_with_index",
      "array_reduce_initial_with_array",
    ], 2),
  ]),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Array",
    member: "sort",
    argumentCount: 0,
    target: Object.freeze({ kind: "instance", name: "sort", receiver: "mut" }),
  }),
  jsCallbackRow("Array", "sort", "mut", "float64", [
    "array_sort_zero", "array_sort_value", "array_sort_compare",
  ], 1),
  ...jsInstanceRows("Map", "mut", ["clear"]),
  jsInstanceParameterRow("Map", "delete", "mut", [receiverArgument(0)]),
  jsInstanceParameterRow("Map", "set", "mut", [receiverArgument(0), receiverArgument(1)]),
  ...["Map", "ReadonlyMap"].flatMap((owner) => [
    Object.freeze({
      ...jsInstanceParameterRow(owner, "get", "imm", [receiverArgument(0)]),
      resultContract: Object.freeze({ kind: "receiver-argument" as const, index: 1, optional: true }),
    }),
    jsInstanceParameterRow(owner, "has", "imm", [receiverArgument(0)]),
  ]),
  ...["Map", "ReadonlyMap"].flatMap((owner) => [
    jsReceiverArrayRow(owner, "keys", Object.freeze({ kind: "receiver-argument", index: 0 })),
    jsReceiverArrayRow(owner, "values", Object.freeze({ kind: "receiver-argument", index: 1 })),
    jsReceiverArrayRow(owner, "entries", Object.freeze({
      kind: "tuple",
      indexes: Object.freeze([0, 1]),
    })),
  ]),
  ...["Map", "ReadonlyMap"].map((owner) => jsCallbackRow(owner, "forEach", "imm", "preserve", [
    "map_for_each_zero", "map_for_each_value", "map_for_each_value_key", "map_for_each_with_map",
  ])),
  ...jsInstanceRows("Set", "mut", ["clear"]),
  jsInstanceParameterRow("Set", "add", "mut", [receiverArgument(0)]),
  jsInstanceParameterRow("Set", "delete", "mut", [receiverArgument(0)]),
  ...["Set", "ReadonlySet"].flatMap((owner) => [
    jsInstanceParameterRow(owner, "has", "imm", [receiverArgument(0)]),
    ...[
      "difference", "intersection", "isDisjointFrom", "isSubsetOf",
      "isSupersetOf", "symmetricDifference", "union",
    ].map((member) => jsInstanceParameterRow(owner, member, "imm", [receiverType])),
  ]),
  ...["Set", "ReadonlySet"].flatMap((owner) => [
    jsReceiverArrayRow(owner, "keys", Object.freeze({ kind: "receiver-argument", index: 0 })),
    jsReceiverArrayRow(owner, "values", Object.freeze({ kind: "receiver-argument", index: 0 })),
    jsReceiverArrayRow(owner, "entries", Object.freeze({
      kind: "tuple",
      indexes: Object.freeze([0, 0]),
    })),
  ]),
  ...["Set", "ReadonlySet"].map((owner) => jsCallbackRow(owner, "forEach", "imm", "preserve", [
    "set_for_each_zero", "set_for_each_value", "set_for_each_value_key", "set_for_each_with_set",
  ])),
  ...jsInstanceRows("Date", "imm", [
    "getTime", ["getUTCDate", "get_utc_date"], ["getUTCDay", "get_utc_day"],
    ["getUTCFullYear", "get_utc_full_year"], ["getUTCHours", "get_utc_hours"],
    ["getUTCMilliseconds", "get_utc_milliseconds"], ["getUTCMinutes", "get_utc_minutes"],
    ["getUTCMonth", "get_utc_month"], ["getUTCSeconds", "get_utc_seconds"],
    ["toJSON", "to_json"], "toString", ["toUTCString", "to_utc_string"], "valueOf",
  ]),
  ...jsInstanceRows("Date", "mut", [
    "setTime", ["setUTCDate", "set_utc_date"], ["setUTCFullYear", "set_utc_full_year"],
    ["setUTCHours", "set_utc_hours"], ["setUTCMilliseconds", "set_utc_milliseconds"],
    ["setUTCMinutes", "set_utc_minutes"], ["setUTCMonth", "set_utc_month"],
    ["setUTCSeconds", "set_utc_seconds"],
  ]),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Date",
    member: "toISOString",
    target: Object.freeze({ kind: "instance", name: "to_iso_string", receiver: "imm" }),
    raises: true,
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Boolean",
    member: "toString",
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "boolean_to_string",
      receiver: "imm",
    }),
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Boolean",
    member: "valueOf",
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "boolean_value_of",
      receiver: "imm",
    }),
  }),
  jsReceiverFunctionRow("Number", "toString", "number_to_string", 0, []),
  Object.freeze({
    ...jsReceiverFunctionRow(
      "Number", "toString", "number_to_string_radix", 1, ["float64"], true,
    ),
    receiverCapability: "integer",
  }),
  jsReceiverFunctionRow("Number", "valueOf", "number_value_of", 0, []),
  jsReceiverFunctionRow("Number", "toFixed", "number_to_fixed", 0, [], true),
  jsReceiverFunctionRow("Number", "toFixed", "number_to_fixed", 1, ["float64"], true),
  jsReceiverFunctionRow(
    "Number", "toExponential", "number_to_exponential_default", 0, [],
  ),
  jsReceiverFunctionRow(
    "Number", "toExponential", "number_to_exponential_digits", 1, ["float64"], true,
  ),
  jsReceiverFunctionRow(
    "Number", "toPrecision", "number_to_precision_default", 0, [],
  ),
  jsReceiverFunctionRow(
    "Number", "toPrecision", "number_to_precision_digits", 1, ["float64"], true,
  ),
  ...jsStaticRows("StringConstructor", ["fromCharCode", ["fromCodePoint", "string_from_code_point", true]]),
  ...jsStaticRows("DateConstructor", ["now", "parse", ["UTC", "date_utc"]]),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "ObjectConstructor",
    member: "is",
    argumentCount: 2,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-value", "js-value"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "object_is",
    }),
  }),
  ...[
    ["keys", "object_keys"],
    ["values", "object_values"],
    ["entries", "object_entries"],
  ].map(([member, name]): MojoSourceProfileCallRow => Object.freeze({
    profile: "js",
    kind: "call",
    owner: "ObjectConstructor",
    member: member!,
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-value"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: name!,
    }),
    raises: true,
  })),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "ObjectConstructor",
    member: "hasOwn",
    argumentCount: 2,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-value", "js-string"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "object_has_own",
    }),
    raises: true,
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Object",
    member: "hasOwnProperty",
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "object_has_own",
      receiver: "imm",
    }),
    raises: true,
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "JSON",
    member: "parse",
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "json_parse",
    }),
    raises: true,
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "JSON",
    member: "stringify",
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-value"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "json_stringify",
    }),
    raises: true,
  }),
  ...["isFinite", "isInteger", "isNaN", "isSafeInteger"].map((member) => Object.freeze({
    profile: "js" as const,
    kind: "call" as const,
    owner: "NumberConstructor",
    member,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["float64"]),
    target: Object.freeze({
      kind: "function" as const,
      modulePath: Object.freeze(["tsonic_js"]),
      name: member === "isNaN" ? "number_is_nan" : `number_${snakeCase(member)}`,
    }),
  })),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "NumberConstructor",
    member: "parseFloat",
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string"]),
    target: Object.freeze({ kind: "function", modulePath: Object.freeze(["tsonic_js"]), name: "number_parse_float" }),
  }),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Global",
    member: "parseFloat",
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: "number_parse_float",
    }),
  }),
  ...[
    ["encodeURIComponent", "encode_uri_component"],
    ["decodeURIComponent", "decode_uri_component"],
  ].map(([member, name]): MojoSourceProfileCallRow => Object.freeze({
    profile: "js",
    kind: "call",
    owner: "Global",
    member: member!,
    argumentCount: 1,
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string"]),
    target: Object.freeze({
      kind: "function",
      modulePath: Object.freeze(["tsonic_js"]),
      name: name!,
    }),
    raises: true,
  })),
  Object.freeze({
    profile: "js",
    kind: "call",
    owner: "NumberConstructor",
    member: "parseInt",
    parameterContract: Object.freeze<MojoSourceProfileParameterContract[]>(["js-string", "float64"]),
    target: Object.freeze({ kind: "function", modulePath: Object.freeze(["tsonic_js"]), name: "number_parse_int" }),
  }),
  ...jsStaticRows("Math", [
    "abs", "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", "cbrt", "ceil",
    "clz32", "cos", "cosh", "exp", "expm1", "floor", "fround", "hypot", "imul", "log",
    "log10", "log1p", "log2", "max", "min", "pow", "random", "round", "sign", "sin",
    "sinh", "sqrt", "tan", "tanh", "trunc",
  ]),
  ...jsStaticRows("Console", [
    ["debug", "console_debug"],
    ["error", "console_error"],
    ["info", "console_info"],
    ["log", "console_log"],
    ["warn", "console_warn"],
  ]),
]);
